### PR TITLE
Fix: resume with floating

### PR DESCRIPTION
**Pull request by ZhenxiZhao**
resume with floating is fixed.
the results of using or not using resume are the same.

and sorry, there are some diffs have no relation with this fix but for the next fix (repack..)

### CODE REVIEW

**Comment by Oblomov** [comment]
Hello @ZhenxiZhao,

I _really_ appreciate the work you've been doing on GPUSPH, but I really cannot review it for merging in the way it's currently submitted, because it's extremely hard to see what is actually being done. Moreover, from what I've seen, there are some changes that I would need to be clarified, and with all things mixed up like this this is essentially impossible to do in a proper way.

I understand that you may want to keep your working directory in its present state for your own projects, but for inclusion in GPUPH these changes need to be cleaned up (there's lots of new files committed that don't really make sense) and split (to separate the two fixes). So please do the following to prepare a proper pull request:

1. start off a new branch, specific for the floating object fix, starting off from your `next` branch: `git checkout -b floating-fix next`;
2. while on the `floating-fix` branch, apply _manually_ the changes needed to fix the floating object resume, and _only_ those changes; do not just merge your `master` branch: just redo the specific changes that fix the floating object resume;
3. commit these changes to the `floating-fix` branch, and push it.
4. open a new pull request from the `floating-fix` branch to the `next` branch in the GPUSPH repository.

I know that this is may seem boring and overly involved, but ti's necessary to be able to properly review the changes. On the upside, for future contributions you can start off with the correct procedure and merges will be much easier to do 8-)

**Comment by ZhenxiZhao** [comment]
I understand.
But I am quite busy these days. I will do this in the next few days.
I need to add these feature to my project before I forget

Also, I need to watch some tutorial.
After reusme and repack. I want to rewrite the pre-process module.
Because I am interested in this article. I think it is very useful coupling with REPACK.
https://link.springer.com/article/10.1007/s42241-021-0031-y

If possible, I  look forward to further cooperation

发件人: ***@***.***>
发送时间: 2021年5月30日 14:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [GPUSPH/gpusph] Fix: resume with floating (#70)


Hello @ZhenxiZhao<https://github.com/ZhenxiZhao>,

I really appreciate the work you've been doing on GPUSPH, but I really cannot review it for merging in the way it's currently submitted, because it's extremely hard to see what is actually being done. Moreover, from what I've seen, there are some changes that I would need to be clarified, and with all things mixed up like this this is essentially impossible to do in a proper way.

I understand that you may want to keep your working directory in its present state for your own projects, but for inclusion in GPUPH these changes need to be cleaned up (there's lots of new files committed that don't really make sense) and split (to separate the two fixes). So please do the following to prepare a proper pull request:

  1.  start off a new branch, specific for the floating object fix, starting off from your next branch: git checkout -b floating-fix next;
  2.  while on the floating-fix branch, apply manually the changes needed to fix the floating object resume, and only those changes; do not just merge your master branch: just redo the specific changes that fix the floating object resume;
  3.  commit these changes to the floating-fix branch, and push it.
  4.  open a new pull request from the floating-fix branch to the next branch in the GPUSPH repository.

I know that this is may seem boring and overly involved, but ti's necessary to be able to properly review the changes. On the upside, for future contributions you can start off with the correct procedure and merges will be much easier to do 8-)

―

**Comment by Oblomov** [comment]
Hello @ZhenxiZhao,

I completely understand about the lack of time. Indeed, if I had some free time I would help you split the patches myself. Maybe when you launch your first long-running GPUSPH simulation you can work on this while you wait for it to finish ;-) (possibly in a separate clone to not mess up with the simulation!) I'll keep this merge request open as a reminder for both of us.

That paper you linked looks very interesting, it would be very useful to generate fluid and boundary particles on both sides of solid objects defined by arbitrary meshes. If you start working on implementing this in GPUSPH, do contact us before-hand (on the forum or on IRC), because we're working on a (backwards-compatible) redesign of the Problem API, and this may fit very well with it.

I'm really looking forward to our future cooperation too.

**Comment by Oblomov** [comment]
Hello @ZhenxiZhao I have filtered the changes pertaining proper resuming of moving objects, and I have integrated in the `next` branch. The patches are somewhat different from your proposed ones, since the fix required changing the on-disk format, and even though we've been a bit sloppy about it in the past, we're trying to be stricter about compatibility more recently.

I have also isolated the changes to the repacking mechanism, which I'm attaching here as a clean patch:
[0001-Repacking-fixes.patch.gz](https://github.com/GPUSPH/gpusph/files/6717695/0001-Repacking-fixes.patch.gz)

This patch needs a more in-depth review than the floating objects resume fix, so I would appreciate it if you try a proper pull request with it this time. My recommendation is the following:

1. update your next branch so that it is level with our next branch (no additional changes);
2. create a new branch starting off `next` (call it with a relevant name, e.g. `fix-repacking`);
3. apply the patch I attached here: you should gunzip it, and then use `git apply` to apply it;
4. verify that the patch still works correctly (I have not tested it, so it's possible I missed something); make any necessary changes in case it doesn't;
5. create a fresh PR with the new branch, so that we can do a proper review (there are some aspects that need clarifying, and a few things that I would suggest we do separately).

One thing I can anticipate is that I would appreciate if you could add a simple problem dedicated just to repacking (e.g. a 3D version of the trapezoidal geometry from the Colagrossi et al. (2012) CPC paper).

I'm closing this PR now, since it was dedicated to the floating object resume fix, that has now been merged in a different form. I'm looking forward to a clean PR with the repacking fix.

**Comment by ZhenxiZhao** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月26日 1:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [GPUSPH/gpusph] Fix: resume with floating (#70)


Hello @ZhenxiZhao<https://github.com/ZhenxiZhao> I have filtered the changes pertaining proper resuming of moving objects, and I have integrated in the next branch. The patches are somewhat different from your proposed ones, since the fix required changing the on-disk format, and even though we've been a bit sloppy about it in the past, we're trying to be stricter about compatibility more recently.

I have also isolated the changes to the repacking mechanism, which I'm attaching here as a clean patch:
0001-Repacking-fixes.patch.gz<https://github.com/GPUSPH/gpusph/files/6717695/0001-Repacking-fixes.patch.gz>

This patch needs a more in-depth review than the floating objects resume fix, so I would appreciate it if you try a proper pull request with it this time. My recommendation is the following:

  1.  update your next branch so that it is level with our next branch (no additional changes);
  2.  create a new branch starting off next (call it with a relevant name, e.g. fix-repacking);
  3.  apply the patch I attached here: you should gunzip it, and then use git apply to apply it;
  4.  verify that the patch still works correctly (I have not tested it, so it's possible I missed something); make any necessary changes in case it doesn't;
  5.  create a fresh PR with the new branch, so that we can do a proper review (there are some aspects that need clarifying, and a few things that I would suggest we do separately).

One thing I can anticipate is that I would appreciate if you could add a simple problem dedicated just to repacking (e.g. a 3D version of the trapezoidal geometry from the Colagrossi et al. (2012) CPC paper).

I'm closing this PR now, since it was dedicated to the floating object resume fix, that has now been merged in a different form. I'm looking forward to a clean PR with the repacking fix.

―

**Comment by ZhenxiZhao** [comment]
Nice to hear that.

I would test REPACK after finish my work in a few weeks.
I am sorry I can work immediately.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月26日 1:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [GPUSPH/gpusph] Fix: resume with floating (#70)


Hello @ZhenxiZhao<https://github.com/ZhenxiZhao> I have filtered the changes pertaining proper resuming of moving objects, and I have integrated in the next branch. The patches are somewhat different from your proposed ones, since the fix required changing the on-disk format, and even though we've been a bit sloppy about it in the past, we're trying to be stricter about compatibility more recently.

I have also isolated the changes to the repacking mechanism, which I'm attaching here as a clean patch:
0001-Repacking-fixes.patch.gz<https://github.com/GPUSPH/gpusph/files/6717695/0001-Repacking-fixes.patch.gz>

This patch needs a more in-depth review than the floating objects resume fix, so I would appreciate it if you try a proper pull request with it this time. My recommendation is the following:

  1.  update your next branch so that it is level with our next branch (no additional changes);
  2.  create a new branch starting off next (call it with a relevant name, e.g. fix-repacking);
  3.  apply the patch I attached here: you should gunzip it, and then use git apply to apply it;
  4.  verify that the patch still works correctly (I have not tested it, so it's possible I missed something); make any necessary changes in case it doesn't;
  5.  create a fresh PR with the new branch, so that we can do a proper review (there are some aspects that need clarifying, and a few things that I would suggest we do separately).

One thing I can anticipate is that I would appreciate if you could add a simple problem dedicated just to repacking (e.g. a 3D version of the trapezoidal geometry from the Colagrossi et al. (2012) CPC paper).

I'm closing this PR now, since it was dedicated to the floating object resume fix, that has now been merged in a different form. I'm looking forward to a clean PR with the repacking fix.

―

**Pull request closed without merging**
